### ISSUE TITLE
Unable to install with .NET Framework 4.7.2

### ISSUE THREAD

**Issue by bfallar3** [binaryfog/NameParser#23]
Any help why I can't install via Nuget with .NET Framework 4.7.2 project?

**Comment by RupW** [comment]
It looks like they dropped support for the .NET Framework (and .NET Standard 2.0) in the 3.x packages in order to use C# 8.0 language features: the latest language version for .NET Framework or .NET Standard 2.0 is C# 7.3.

You can still install version 2.5.1 from NuGet. It might be possible to back-port the most recent code to C# 7.3 but I don't know if that's worth it or not.

**Comment by binaryfog** [comment]
As @RupW said, we dropped support for C# 7.3 in the  3.x packages.  Please follow @RupW suggestion.
Thanks @RupW for help !

Catalin
